apiVersion: extensions/v1beta1
kind: Service
apiVersion: v1
metadata:
  name: "notify-stub-service"
spec:
  selector:
    app: "http-server"
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: http2
  - protocol: TCP
    port: 8091
    targetPort: 8000
    name: metrics
  - protocol: TCP
    port: 8443
    targetPort: 8443
    name: application-https
